name: Assets Build

on:
  push:
    paths:
      # - 'assets/**'
      - '**'
  pull_request:
    paths:
      # - 'assets/**'
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup Node for JS build
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: assets/js/package-lock.json
    
    # Build JS assets
    - name: Install JS Dependencies
      working-directory: ./assets/js
      run: npm ci

    - name: Test JS Assets
      working-directory: ./assets/js
      run: npm test

    - name: Build JS Assets
      working-directory: ./assets/js
      run: npm run build

    # Setup Java for API build
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # Build API
    - name: Build Assets API
      working-directory: ./assets/api
      run: mvn clean install -Drevision=$(git rev-parse --short HEAD)

    # Docker steps
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/trunk'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker image
      if: github.ref == 'refs/heads/trunk'
      working-directory: ./assets
      run: |
        if [ -f api/target/restful-booker-platform-assets-*-exec.jar ]; then
          VERSION=$(ls api/target/restful-booker-platform-assets-*-exec.jar | cut -d '-' -f 5 | cut -c1-11)
          docker build -t mwinteringham/restfulbookerplatform_assets:$VERSION .
          docker push mwinteringham/restfulbookerplatform_assets:$VERSION
        else
          echo "Assets JAR file not found"
          exit 1
        fi 