name: Assets Build

on:
  push:
    paths:
      - 'assets/**'
  pull_request:
    paths:
      - 'assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup Node for JS build
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: assets/package-lock.json
    
    # Build JS assets
    - name: Install JS Dependencies
      working-directory: ./assets
      run: npm ci

    - name: Test JS Assets
      working-directory: ./assets
      run: npm test

    # Docker steps
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/trunk'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker image
      if: github.ref == 'refs/heads/trunk'
      working-directory: ./assets
      run: |
        VERSION=$(grep '"version":' package.json | sed 's/.*"version": "\(.*\)",/\1/').$(git rev-parse --short HEAD)
        docker build -t mwinteringham/restfulbookerplatform_assets:latest .
        docker push mwinteringham/restfulbookerplatform_assets:$latest
        echo "VERSION=$VERSION" >> $GITHUB_ENV
