name: Auth Service Build

on:
  push:
    paths:
      - 'auth/**'
  pull_request:
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build Auth Service
      working-directory: ./auth
      run: mvn clean install -Drevision=$(git rev-parse --short HEAD)

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/trunk'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker image
      if: github.ref == 'refs/heads/trunk'
      working-directory: ./auth
      run: |
        if [ -f target/restful-booker-platform-auth-*-exec.jar ]; then
          VERSION=$(ls target/restful-booker-platform-auth-*-exec.jar | cut -d '-' -f 5 | cut -c1-11)
          docker build -t mwinteringham/restfulbookerplatform_auth:$VERSION .
          docker push mwinteringham/restfulbookerplatform_auth:$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          echo "Auth JAR file not found"
          exit 1
        fi
