name: Room Service Build

on:
  push:
    paths:
      - 'room/**'
  pull_request:
    paths:
      - 'room/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build Room Service
      working-directory: ./room
      run: mvn clean install -Drevision=$(git rev-parse --short HEAD)
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/trunk'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and Push Docker image
      if: github.ref == 'refs/heads/trunk'
      working-directory: ./room
      run: |
        if [ -f target/restful-booker-platform-room-*-exec.jar ]; then
          VERSION=$(ls target/restful-booker-platform-room-*-exec.jar | cut -d '-' -f 5 | cut -c1-11)
          docker build -t mwinteringham/restfulbookerplatform_room:$VERSION .
          docker push mwinteringham/restfulbookerplatform_room:$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          echo "Room JAR file not found"
          exit 1
        fi
